[build-system]
requires = [
    "scikit-build-core>=0.5.0",
    "pybind11>=2.10.0",
]
build-backend = "scikit_build_core.build"

[project]
name = "duvc-ctl"
version = "2.0.0-rc3"
authors = [
    { name = "allanhanan", email = "allan.hanan04@gmail.com" }
]
description = "DirectShow UVC Camera Control Library"
readme = "PYPI_README.md"
license = { file = "../../LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: C++",
    "Topic :: Multimedia :: Video",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Hardware :: Hardware Drivers",
]
keywords = [
    "camera", "uvc", "directshow", "ptz", "video", "control", "webcam"
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "isort",
    "mypy",
    "build",
    "twine",
]

[project.urls]
Homepage = "https://github.com/allanhanan/duvc-ctl"
Repository = "https://github.com/allanhanan/duvc-ctl"
Documentation = "https://github.com/allanhanan/duvc-ctl/blob/main/README.md"
"Bug Reports" = "https://github.com/allanhanan/duvc-ctl/issues"

[tool.scikit-build]
# Protect the configuration against future changes in scikit-build-core
minimum-version = "0.5"

# Build directory
build-dir = "build/{wheel_tag}"

# Source directory containing CMakeLists.txt
cmake.source-dir = "../.."

# CMake arguments
cmake.args = [
    "-DDUVC_BUILD_PYTHON=ON",
    "-DDUVC_BUILD_CLI=OFF", 
    "-DDUVC_BUILD_STATIC=ON",
    "-DDUVC_BUILD_C_API=OFF",
]

# Wheel options
wheel.packages = ["duvc_ctl"]

# Only build for Windows
wheel.expand-macos-universal-tags = false

[tool.scikit-build.cmake.define]
DUVC_BUILD_PYTHON = "ON"
DUVC_BUILD_CLI = "OFF"
DUVC_BUILD_STATIC = "OFF"
DUVC_BUILD_C_API = "OFF"

[tool.cibuildwheel]
# Only build for Windows since this is Windows-only
build = "cp3{8,9,10,11,12}-win_amd64"
skip = "pp*"  # Skip PyPy builds

[tool.cibuildwheel.windows]
before-build = "pip install cmake pybind11[global] delvewheel"
repair-wheel-command = "python bindings/python/repair_wheel.py {wheel} {dest_dir}"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
