duvc-ctl: bindings.cpp File Reference
bindings.cpp File Reference
#include "duvc-ctl/core.h"
#include <vector>
#include <mutex>
Macros
#define DUVCC_API __declspec(dllexport)
Functions
void duvc_refresh_devices ()
int duvc_get_device_count ()
const wchar_t * duvc_get_device_name (int index)
const wchar_t * duvc_get_device_path (int index)
int duvc_is_device_connected (int index)
void duvc_clear_cache ()
int duvc_cam_get_range (int index, int camProp, int *outMin, int *outMax, int *outStep, int *outDef, int *outModeAuto)
int duvc_cam_get (int index, int camProp, int *outValue, int *outModeAuto)
int duvc_cam_set (int index, int camProp, int value, int modeAuto)
int duvc_vid_get_range (int index, int vidProp, int *outMin, int *outMax, int *outStep, int *outDef, int *outModeAuto)
int duvc_vid_get (int index, int vidProp, int *outValue, int *outModeAuto)
int duvc_vid_set (int index, int vidProp, int value, int modeAuto)
Variables
static std::mutex g_devices_mutex
static std::vector< duvc::Device > g_devices
Macro Definition Documentation
DUVCC_API
#define DUVCC_API __declspec(dllexport)
Definition at line 6 of file bindings.cpp.
Function Documentation
duvc_cam_get()
int duvc_cam_get (int index, int camProp, int * outValue, int * outModeAuto)
Definition at line 77 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::get(), duvc::list_devices(), and duvc::PropSetting::value.
duvc_cam_get_range()
int duvc_cam_get_range (int index, int camProp, int * outMin, int * outMax, int * outStep, int * outDef, int * outModeAuto)
Definition at line 61 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::get_range(), duvc::list_devices(), and duvc::PropRange::min.
duvc_cam_set()
int duvc_cam_set (int index, int camProp, int value, int modeAuto)
Definition at line 90 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::list_devices(), duvc::Manual, and duvc::set().
duvc_clear_cache()
void duvc_clear_cache ()
Definition at line 57 of file bindings.cpp.
References duvc::clear_connection_cache().
duvc_get_device_count()
int duvc_get_device_count ()
Definition at line 22 of file bindings.cpp.
References g_devices, g_devices_mutex, and duvc::list_devices().
duvc_get_device_name()
const wchar_t * duvc_get_device_name (int index)
Definition at line 30 of file bindings.cpp.
References g_devices, g_devices_mutex, and duvc::list_devices().
duvc_get_device_path()
const wchar_t * duvc_get_device_path (int index)
Definition at line 39 of file bindings.cpp.
References g_devices, g_devices_mutex, and duvc::list_devices().
duvc_is_device_connected()
int duvc_is_device_connected (int index)
Definition at line 48 of file bindings.cpp.
References g_devices, g_devices_mutex, duvc::is_device_connected(), and duvc::list_devices().
duvc_refresh_devices()
void duvc_refresh_devices ()
Definition at line 17 of file bindings.cpp.
References g_devices, g_devices_mutex, and duvc::list_devices().
duvc_vid_get()
int duvc_vid_get (int index, int vidProp, int * outValue, int * outModeAuto)
Definition at line 117 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::get(), duvc::list_devices(), and duvc::PropSetting::value.
duvc_vid_get_range()
int duvc_vid_get_range (int index, int vidProp, int * outMin, int * outMax, int * outStep, int * outDef, int * outModeAuto)
Definition at line 101 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::get_range(), duvc::list_devices(), and duvc::PropRange::min.
duvc_vid_set()
int duvc_vid_set (int index, int vidProp, int value, int modeAuto)
Definition at line 130 of file bindings.cpp.
References duvc::Auto, g_devices, g_devices_mutex, duvc::list_devices(), duvc::Manual, and duvc::set().
Variable Documentation
g_devices
std::vector<duvc::Device> g_devices static
Definition at line 15 of file bindings.cpp.
Referenced by duvc_cam_get(), duvc_cam_get_range(), duvc_cam_set(), duvc_get_device_count(), duvc_get_device_name(), duvc_get_device_path(), duvc_is_device_connected(), duvc_refresh_devices(), duvc_vid_get(), duvc_vid_get_range(), and duvc_vid_set().
g_devices_mutex
std::mutex g_devices_mutex static
Definition at line 14 of file bindings.cpp.
Referenced by duvc_cam_get(), duvc_cam_get_range(), duvc_cam_set(), duvc_get_device_count(), duvc_get_device_name(), duvc_get_device_path(), duvc_is_device_connected(), duvc_refresh_devices(), duvc_vid_get(), duvc_vid_get_range(), and duvc_vid_set().