duvc-ctl: duvc::com_ptr< T > Class Template Reference
duvc::com_ptr< T > Class Template Reference
Public Member Functions
com_ptr () noexcept=default
com_ptr (T *p) noexcept
~com_ptr ()
com_ptr (const com_ptr &)=delete
com_ptr & operator= (const com_ptr &)=delete
com_ptr (com_ptr &&o) noexcept
com_ptr & operator= (com_ptr &&o) noexcept
T * get () const noexcept
T ** put () noexcept
T * operator-> () const noexcept
operator bool () const noexcept
void reset () noexcept
Detailed Description
template<typename T>
class duvc::com_ptr< T >
Definition at line 82 of file core.cpp.
Constructor & Destructor Documentation
com_ptr() [1/4]
template<typename T > duvc::com_ptr< T >::com_ptr () default noexcept
com_ptr() [2/4]
template<typename T > duvc::com_ptr< T >::com_ptr (T * p) inline explicit noexcept
Definition at line 85 of file core.cpp.
~com_ptr()
template<typename T > duvc::com_ptr< T >::~com_ptr () inline
Definition at line 86 of file core.cpp.
References duvc::com_ptr< T >::reset().
com_ptr() [3/4]
template<typename T > duvc::com_ptr< T >::com_ptr (const com_ptr< T > &) delete
com_ptr() [4/4]
template<typename T > duvc::com_ptr< T >::com_ptr (com_ptr< T > && o) inline noexcept
Definition at line 91 of file core.cpp.
Member Function Documentation
get()
template<typename T > T * duvc::com_ptr< T >::get () const inline noexcept
Definition at line 97 of file core.cpp.
operator bool()
template<typename T > duvc::com_ptr< T >::operator bool () const inline explicit noexcept
Definition at line 100 of file core.cpp.
operator->()
template<typename T > T * duvc::com_ptr< T >::operator-> () const inline noexcept
Definition at line 99 of file core.cpp.
operator=() [1/2]
template<typename T > com_ptr & duvc::com_ptr< T >::operator= (com_ptr< T > && o) inline noexcept
Definition at line 92 of file core.cpp.
References duvc::com_ptr< T >::reset().
operator=() [2/2]
template<typename T > com_ptr & duvc::com_ptr< T >::operator= (const com_ptr< T > &) delete
put()
template<typename T > T ** duvc::com_ptr< T >::put () inline noexcept
Definition at line 98 of file core.cpp.
References duvc::com_ptr< T >::reset().
reset()
template<typename T > void duvc::com_ptr< T >::reset () inline noexcept
Definition at line 101 of file core.cpp.
Referenced by duvc::com_ptr< T >::operator=(), duvc::com_ptr< T >::put(), and duvc::com_ptr< T >::~com_ptr().
The documentation for this class was generated from the following file:
core.cpp