duvc-ctl: duvc::Error Class Reference
duvc::Error Class Reference
Error information with context.
#include <duvc-ctl/core/result.h>
Public Member Functions
Error (ErrorCode code, std::string message="")
Create error with code and message.
Error (std::error_code code, std::string message="")
Create error from system error.
ErrorCode code () const
Get error code.
const std::string & message () const
Get error message.
std::string description () const
Get full error description.
Detailed Description
Error information with context.
Definition at line 41 of file result.h.
Constructor & Destructor Documentation
Error() [1/2]
duvc::Error::Error (ErrorCode code, std::string message = "")
Create error with code and message.
Parameters
code Error code
message Descriptive error message
Definition at line 35 of file result.cpp.
Error() [2/2]
duvc::Error::Error (std::error_code code, std::string message = "")
Create error from system error.
Parameters
code System error code
message Additional context message
Definition at line 38 of file result.cpp.
References code().
Member Function Documentation
code()
ErrorCode duvc::Error::code () const inline
Get error code.
Definition at line 58 of file result.h.
Referenced by Error().
description()
std::string duvc::Error::description () const
Get full error description.
Definition at line 47 of file result.cpp.
References duvc::to_string().
message()
const std::string & duvc::Error::message () const inline
Get error message.
Definition at line 61 of file result.h.
The documentation for this class was generated from the following files:
core/result.h
core/result.cpp