duvc-ctl: duvc::DeviceCapabilities Class Reference
duvc::DeviceCapabilities Class Reference
Complete device capability snapshot.
#include <duvc-ctl/core/capability.h>
Public Member Functions
DeviceCapabilities (const Device &device)
Create capabilities snapshot for device.
const PropertyCapability & get_camera_capability (CamProp prop) const
Get camera property capability.
const PropertyCapability & get_video_capability (VidProp prop) const
Get video property capability.
bool supports_camera_property (CamProp prop) const
Check if camera property is supported.
bool supports_video_property (VidProp prop) const
Check if video property is supported.
std::vector< CamProp > supported_camera_properties () const
Get list of supported camera properties.
std::vector< VidProp > supported_video_properties () const
Get list of supported video properties.
const Device & device () const
Get the device this capability snapshot is for.
bool is_device_accessible () const
Check if device is connected and accessible.
Result< void > refresh ()
Refresh capability snapshot.
Detailed Description
Complete device capability snapshot.
Definition at line 35 of file capability.h.
Constructor & Destructor Documentation
DeviceCapabilities()
duvc::DeviceCapabilities::DeviceCapabilities (const Device & device) explicit
Create capabilities snapshot for device.
Parameters
device Device to analyze
Definition at line 19 of file capability.cpp.
References duvc::is_device_connected().
Member Function Documentation
device()
const Device & duvc::DeviceCapabilities::device () const inline
Get the device this capability snapshot is for.
Returns
Device reference
Definition at line 87 of file capability.h.
get_camera_capability()
const PropertyCapability & duvc::DeviceCapabilities::get_camera_capability (CamProp prop) const
Get camera property capability.
Parameters
prop Camera property
Returns
Property capability info
Definition at line 89 of file capability.cpp.
Referenced by duvc_get_camera_capability(), and supports_camera_property().
get_video_capability()
const PropertyCapability & duvc::DeviceCapabilities::get_video_capability (VidProp prop) const
Get video property capability.
Parameters
prop Video property
Returns
Property capability info
Definition at line 95 of file capability.cpp.
Referenced by duvc_get_video_capability(), and supports_video_property().
is_device_accessible()
bool duvc::DeviceCapabilities::is_device_accessible () const inline
Check if device is connected and accessible.
Returns
true if device is accessible
Definition at line 93 of file capability.h.
Referenced by duvc_capabilities_is_device_accessible(), and duvc::get_device_capabilities().
refresh()
Result< void > duvc::DeviceCapabilities::refresh ()
Refresh capability snapshot.
Returns
Result indicating success or error
Definition at line 128 of file capability.cpp.
References duvc::DeviceNotFound, duvc::is_device_connected(), and duvc::Ok().
Referenced by duvc_refresh_device_capabilities().
supported_camera_properties()
std::vector< CamProp > duvc::DeviceCapabilities::supported_camera_properties () const
Get list of supported camera properties.
Returns
Vector of supported camera properties
Definition at line 108 of file capability.cpp.
Referenced by duvc_get_supported_camera_properties().
supported_video_properties()
std::vector< VidProp > duvc::DeviceCapabilities::supported_video_properties () const
Get list of supported video properties.
Returns
Vector of supported video properties
Definition at line 118 of file capability.cpp.
Referenced by duvc_get_supported_video_properties().
supports_camera_property()
bool duvc::DeviceCapabilities::supports_camera_property (CamProp prop) const
Check if camera property is supported.
Parameters
prop Camera property
Returns
true if supported
Definition at line 100 of file capability.cpp.
References get_camera_capability().
Referenced by duvc_supports_camera_property().
supports_video_property()
bool duvc::DeviceCapabilities::supports_video_property (VidProp prop) const
Check if video property is supported.
Parameters
prop Video property
Returns
true if supported
Definition at line 104 of file capability.cpp.
References get_video_capability().
Referenced by duvc_supports_video_property().
The documentation for this class was generated from the following files:
core/capability.h
core/capability.cpp