duvc-ctl: duvc::KsPropertySet Class Reference
duvc::KsPropertySet Class Reference
RAII wrapper for IKsPropertySet interface.
#include <duvc-ctl/platform/windows/ks_properties.h>
Public Member Functions
KsPropertySet (const Device &device)
Create KsPropertySet from device.
~KsPropertySet ()
Destructor.
KsPropertySet (const KsPropertySet &)=delete
KsPropertySet & operator= (const KsPropertySet &)=delete
KsPropertySet (KsPropertySet &&) noexcept
KsPropertySet & operator= (KsPropertySet &&) noexcept
bool is_valid () const
Check if property set is valid.
Result< uint32_t > query_support (const GUID &property_set, uint32_t property_id)
Query property support.
Result< std::vector< uint8_t > > get_property (const GUID &property_set, uint32_t property_id)
Get property data.
Result< void > set_property (const GUID &property_set, uint32_t property_id, const std::vector< uint8_t > &data)
Set property data.
template<typename T >
Result< T > get_property_typed (const GUID &property_set, uint32_t property_id)
Get typed property value.
template<typename T >
Result< void > set_property_typed (const GUID &property_set, uint32_t property_id, const T &value)
Set typed property value.
Detailed Description
RAII wrapper for IKsPropertySet interface.
Definition at line 23 of file ks_properties.h.
Constructor & Destructor Documentation
KsPropertySet() [1/3]
duvc::KsPropertySet::KsPropertySet (const Device & device) explicit
Create KsPropertySet from device.
Parameters
device Device to get property set from
Definition at line 23 of file ks_properties.cpp.
References duvc::open_device_filter().
~KsPropertySet()
duvc::KsPropertySet::~KsPropertySet () default
Destructor.
KsPropertySet() [2/3]
duvc::KsPropertySet::KsPropertySet (const KsPropertySet &) delete
KsPropertySet() [3/3]
duvc::KsPropertySet::KsPropertySet (KsPropertySet &&) default noexcept
Member Function Documentation
get_property()
Result< std::vector< uint8_t > > duvc::KsPropertySet::get_property (const GUID & property_set, uint32_t property_id)
Get property data.
Parameters
property_set Property set GUID
property_id Property ID
Returns
Result containing property data or error
Definition at line 70 of file ks_properties.cpp.
References duvc::decode_hresult(), is_valid(), duvc::Ok(), duvc::PropertyNotSupported, and duvc::SystemError.
Referenced by get_property_typed().
get_property_typed()
template<typename T > template Result< bool > duvc::KsPropertySet::get_property_typed< bool > (const GUID & property_set, uint32_t property_id)
Get typed property value.
Template Parameters
T Property value type
Parameters
property_set Property set GUID
property_id Property ID
Returns
Result containing typed value or error
Definition at line 124 of file ks_properties.cpp.
References duvc::Result< T >::error(), get_property(), duvc::InvalidValue, duvc::Result< T >::is_ok(), duvc::Ok(), and duvc::Result< T >::value().
is_valid()
bool duvc::KsPropertySet::is_valid () const
Check if property set is valid.
Returns
true if property set can be used
Definition at line 46 of file ks_properties.cpp.
Referenced by get_property(), query_support(), and set_property().
operator=() [1/2]
KsPropertySet & duvc::KsPropertySet::operator= (const KsPropertySet &) delete
operator=() [2/2]
KsPropertySet & duvc::KsPropertySet::operator= (KsPropertySet &&) default noexcept
query_support()
Result< uint32_t > duvc::KsPropertySet::query_support (const GUID & property_set, uint32_t property_id)
Query property support.
Parameters
property_set Property set GUID
property_id Property ID
Returns
Result containing support flags or error
Definition at line 50 of file ks_properties.cpp.
References duvc::decode_hresult(), is_valid(), duvc::Ok(), duvc::PropertyNotSupported, and duvc::SystemError.
set_property()
Result< void > duvc::KsPropertySet::set_property (const GUID & property_set, uint32_t property_id, const std::vector< uint8_t > & data)
Set property data.
Parameters
property_set Property set GUID
property_id Property ID
data Property data to set
Returns
Result indicating success or error
Definition at line 103 of file ks_properties.cpp.
References duvc::decode_hresult(), is_valid(), duvc::Ok(), and duvc::SystemError.
Referenced by set_property_typed().
set_property_typed()
template<typename T > template Result< void > duvc::KsPropertySet::set_property_typed< bool > (const GUID & property_set, uint32_t property_id, const T & value)
Set typed property value.
Template Parameters
T Property value type
Parameters
property_set Property set GUID
property_id Property ID
value Property value to set
Returns
Result indicating success or error
Definition at line 145 of file ks_properties.cpp.
References set_property().
The documentation for this class was generated from the following files:
platform/windows/ks_properties.h
platform/windows/ks_properties.cpp