duvc-ctl: duvc::Camera Class Reference
duvc::Camera Class Reference
RAII camera handle for simplified device management.
#include <duvc-ctl/core/camera.h>
Public Member Functions
Camera (const Device &device)
Create camera handle for device.
Camera (int device_index)
Create camera handle by device index.
~Camera ()
Destructor - automatically releases device connection.
Camera (const Camera &)=delete
Camera & operator= (const Camera &)=delete
Camera (Camera &&) noexcept
Camera & operator= (Camera &&) noexcept
bool is_valid () const
Check if camera is valid and connected.
const Device & device () const
Get the underlying device information.
Result< PropSetting > get (CamProp prop)
Get camera property value.
Result< void > set (CamProp prop, const PropSetting &setting)
Set camera property value.
Result< PropRange > get_range (CamProp prop)
Get camera property range.
Result< PropSetting > get (VidProp prop)
Get video processing property value.
Result< void > set (VidProp prop, const PropSetting &setting)
Set video processing property value.
Result< PropRange > get_range (VidProp prop)
Get video processing property range.
Detailed Description
RAII camera handle for simplified device management.
This class provides a high-level interface for camera control, automatically managing device connections and providing a clean API.
Definition at line 23 of file camera.h.
Constructor & Destructor Documentation
Camera() [1/4]
duvc::Camera::Camera (const Device & device) explicit
Create camera handle for device.
Parameters
device Device to connect to
Definition at line 12 of file camera.cpp.
Camera() [2/4]
duvc::Camera::Camera (int device_index) explicit
Create camera handle by device index.
Parameters
device_index Index from list_devices()
Definition at line 14 of file camera.cpp.
References duvc::list_devices().
~Camera()
duvc::Camera::~Camera () default
Destructor - automatically releases device connection.
Camera() [3/4]
duvc::Camera::Camera (const Camera &) delete
Camera() [4/4]
duvc::Camera::Camera (Camera &&) default noexcept
Member Function Documentation
device()
const Device & duvc::Camera::device () const inline
Get the underlying device information.
Returns
Device structure
Definition at line 56 of file camera.h.
get() [1/2]
Result< PropSetting > duvc::Camera::get (CamProp prop)
Get camera property value.
Parameters
prop Camera property to query
Returns
Result containing property setting or error
Definition at line 38 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
Referenced by duvc_get_multiple_camera_properties(), duvc_get_multiple_video_properties(), duvc_set_multiple_camera_properties(), and duvc_set_multiple_video_properties().
get() [2/2]
Result< PropSetting > duvc::Camera::get (VidProp prop)
Get video processing property value.
Parameters
prop Video property to query
Returns
Result containing property setting or error
Definition at line 79 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
get_range() [1/2]
Result< PropRange > duvc::Camera::get_range (CamProp prop)
Get camera property range.
Parameters
prop Camera property to query
Returns
Result containing property range or error
Definition at line 65 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
get_range() [2/2]
Result< PropRange > duvc::Camera::get_range (VidProp prop)
Get video processing property range.
Parameters
prop Video property to query
Returns
Result containing property range or error
Definition at line 106 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
is_valid()
bool duvc::Camera::is_valid () const
Check if camera is valid and connected.
Returns
true if camera can be used
Definition at line 27 of file camera.cpp.
References duvc::is_device_connected(), and is_valid().
Referenced by is_valid().
operator=() [1/2]
Camera & duvc::Camera::operator= (Camera &&) default noexcept
operator=() [2/2]
Camera & duvc::Camera::operator= (const Camera &) delete
set() [1/2]
Result< void > duvc::Camera::set (CamProp prop, const PropSetting & setting)
Set camera property value.
Parameters
prop Camera property to set
setting New property setting
Returns
Result indicating success or error
Definition at line 52 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
Referenced by duvc_set_multiple_camera_properties(), and duvc_set_multiple_video_properties().
set() [2/2]
Result< void > duvc::Camera::set (VidProp prop, const PropSetting & setting)
Set video processing property value.
Parameters
prop Video property to set
setting New property setting
Returns
Result indicating success or error
Definition at line 93 of file camera.cpp.
References duvc::DeviceNotFound, duvc::Ok(), and duvc::PropertyNotSupported.
The documentation for this class was generated from the following files:
core/camera.h
core/camera.cpp